In [1]:
import numpy as np
data = np.loadtxt("data.csv", delimiter = ",")

In [3]:
x = data[:, 0:1]
y = data[:, 1:2]
from sklearn import model_selection
x_train, x_test, y_train, y_test = model_selection.train_test_split(x,y)

In [4]:
def fit(x, y):
    m = ((x*y).mean() - x.mean()*y.mean())/((x*x).mean() - x.mean()*x.mean());
    c = y.mean() - m*x.mean()
    return m, c

In [6]:
def predict(x, m, c):
    predictions = x*m;
    for i in range(len(predictions)):
        predictions[i]+=c;
    return predictions

In [8]:
def cost(x, y, m, c):
    predictions = x*m;
    for i in range(len(predictions)):
        predictions[i]+=c;
    ans = 0;
    for i in range(len(predictions)):
        ans += (predictions[i]-y[i])**2
    return ans/len(predictions)

In [10]:
def score(x, y, m, c):
    predictions = x*m;
    for i in range(len(predictions)):
        predictions[i]+=c;
    u = 0
    v = 0
    for i in range(len(predictions)):
        u+=(y[i]-predictions[i])**2
        v+=(y[i] - y.mean())**2
    
    score = 1 - u/v;
    return score

In [9]:
m, c = fit(x_train, y_train)
predictions = predict(x_test, m, c)
print(m)
print(c)
print(predictions)
print(cost(x_train, y_train, m, c))

1.3495949637640587
6.236733541123755
[[79.58942625]
 [68.6298131 ]
 [51.93970752]
 [56.07737894]
 [78.54138836]
 [84.22742961]
 [61.70871047]
 [89.27779485]
 [55.41058848]
 [73.81519871]
 [57.52874875]
 [77.15796838]
 [70.30961769]
 [73.76989322]
 [98.44019883]
 [76.20673668]
 [65.84031232]
 [69.23883422]
 [82.79548784]
 [72.3073542 ]
 [67.56304496]
 [81.55187023]
 [59.27523083]
 [83.58202555]
 [62.54274824]]
[119.02485533]


In [11]:
score(x_test, y_test, m, c)

array([0.53979766])

In [12]:
score(x_train, y_train, m, c)

array([0.60903068])